"""
Django settings for BasicBlogApp project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from .local_settings import *
#from .production_settings import *

#import socket
#if socket.gethostname() == "AbubakrPC":
#   from .local_settings import *
