# Generated by Django 4.2.2 on 2023-08-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='brief_description',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
