# Generated by Django 4.2.2 on 2023-08-22 23:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='webpages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webpage_type', models.CharField(choices=[('ABOUT', 'About'), ('TERMS', 'Terms'), ('PRIVACY', 'Privacy')], max_length=8)),
                ('HeaderTitle', models.CharField(max_length=100)),
                ('Content', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
